### ISSUE TITLE
Idea: A count at the top of the page?

### ISSUE THREAD

**Issue by username-is-required** [Tanza3D/reddark#2]
Just an idea I had - maybe just a sentence at the top of the page, like `[X] subreddits have gone dark`, `[X]/[Y] subreddits have gone dark`, or any different wording (there’s probably a better way of wording it that I can’t think of right now). I guess as a way of being able to tell at an immediate glance how many subreddits have gone private at that time.

Also thanks for building the site! Will be fun to watch on June 12th

**Comment by Tanza3D** [comment]
done!
