### ISSUE TITLE
styling slightly broken on mobile after update

### ISSUE THREAD

**Issue by username-is-required** [Tanza3D/reddark#23]
since 02ca61b, the styling has slightly broken when viewing the site on mobile (iPhone 11, Safari on iOS):

1) the ‘X/Y subreddits are currently dark’ line now breaks as i scroll down the page (see screenshot)
2) there is now no longer two columns on the page, only 1 - it might be a minor thing but having 2 cols rather than 1 made it easier to take in the site

![IMG_9301](https://github.com/Tanza3D/reddark/assets/136007111/2c91bc43-c385-457f-b800-0ee9774759b2)

i apologise for giving you another styling headache

**Comment by Tanza3D** [comment]
oh, no worries, fixed!
