### ISSUE TITLE
It appears when a third thread was created on /r/ModCoord (5k and under) all those subreddits were lost on reddark

### ISSUE THREAD

**Issue by reddituser123** [Tanza3D/reddark#26]

**Comment by username-is-required** [comment]
that would be because the app is currently only set to scrape from the two threads, and doesn’t know the third thread exists. #25 should fix this

**Comment by username-is-required** [comment]
although actually looking at #24 the problem might be being solved anyway by getting the app to refer to the wiki page rather than the threads

**Comment by burtek** [comment]
should be already fixed by #29
