### ISSUE TITLE
Website is not working - 500 and 502 errors

### ISSUE THREAD

**Issue by burtek** [Tanza3D/reddark#30]
![image](https://github.com/Tanza3D/reddark/assets/2940958/7bcf3184-7ebe-4e69-8b27-fbea83d33d2b)
![image](https://github.com/Tanza3D/reddark/assets/2940958/4471171c-0279-44dd-bcb9-8a4b58a4bb08)

**Comment by burtek** [comment]
Nevermind, when website finally loaded I saw this:
![image](https://github.com/Tanza3D/reddark/assets/2940958/9b01aa94-c2ac-483c-aebf-2719133b99c1)

**Comment by Tanza3D** [comment]
yeah things are, not going good, trying to fix them, seems like a bad configuration with nginx and such more than anything

**Comment by burtek** [comment]
as it usually happens with quickly bootstrapped webapps that suddenly get too much attention. Fingers crossed you're gonna handle this :)

**Comment by Tanza3D** [comment]
i hit the max files opened limit on linux lmao, took a while of changing stuff and then more issues popped up after wards but finally now seems all good!
