### ISSUE TITLE
Counter?

### ISSUE THREAD

**Issue by DevilXD** [Tanza3D/reddark#31]
Hi. I've wanted to suggest a simple improvement to the site - a counter showing how many subs are currently private. Big font, up top of the center of the page would be cool, although of course I'm not the one to decide where to place it or how to structure it. I just thought it'd be a really good site addition.

**Comment by Tanza3D** [comment]
sounds neat

**Comment by simonk83** [comment]
<img width="418" alt="Screen Shot 2023-06-11 at 10 15 38 pm" src="https://github.com/Tanza3D/reddark/assets/518440/166c993e-3e47-4e73-98fb-1fc344fb684a">

Isn't that what this is?

**Comment by DevilXD** [comment]
Actually, I'm blind. There already is a counter, but it's so small it's not really noticeable. My suggestion still stands though, it'd be cool to have it moved/changed to something more distinguished, if possible.

**Comment by Tanza3D** [comment]
![image](https://github.com/Tanza3D/reddark/assets/33783503/fe6b76af-75cd-415b-bd10-a3172fbb3b87)
big counter

**Comment by DevilXD** [comment]
That's... not entirely what I've imagined. Why is it a toggle? It should be a part of the main page, not something you have to click on.

Something like this? Sorry for a quick paint mockup, but I think an image describes it better.
![obraz](https://github.com/Tanza3D/reddark/assets/4180725/fd311c1d-7e47-4f9a-8d86-4271e18439b8)
