### ISSUE TITLE
delay between http calls

### ISSUE THREAD

**Issue by username-is-required** [Tanza3D/reddark#35]
[not an issue, just using this as a place to ask a question/discuss]

if i’m understanding the most recent code (that introduces a delay between http requests) correctly, then it works by incrementing the delay between requests by 1ms after every request. meaning that for 5000 subreddits, one run of `updateStatus` would take approximately `5000 + 4999 + 4998 + … + 1 = 12,502,500ms` (around 208 minutes) to complete. however, the website seems to be detecting new privated subreddits quicker than that.

am i missing something here? (i feel like i am)

as a side note, i’ve chucked a branch of my fork onto a digitalocean instance, and i’m currently experimenting with trying to find the lowest delay between requests where the reddit api doesn’t start rate-limiting. in case the info is helpful to you, i’m currently down to ~80ms~ 51ms between requests with no rate-limiting. (i can keep you updated with how low the delay can go if it would be helpful)

**Comment by Tanza3D** [comment]
5000ms is only 5 seconds, no?

**Comment by username-is-required** [comment]
yeah, but then (again, unless i’m misunderstanding it), by the end of the requests being sent off by `updateStatus`, there’d be a 5 second delay between *each request* being sent - and so calculating what the delays would up to overall would leave you with 12,502,500ms or 208min.

again though i feel like i *must* be misunderstanding something here

**Comment by Tanza3D** [comment]
no, it'd be a 1ms delay between each request sent

**Comment by username-is-required** [comment]
i’m slightly confused

at the start of each call to `updateStatus`, the delay is set to 0ms:

https://github.com/Tanza3D/reddark/blob/6541de71a1eac9da5316cce51f9058e7688c7f8d/main.js#L114

then, after the request for the subreddit data is prepared, the delay increases by 1ms

https://github.com/Tanza3D/reddark/blob/6541de71a1eac9da5316cce51f9058e7688c7f8d/main.js#L186

wouldn’t that then mean that by the end of each run of `updateStatus`, the delay is reaching 5000+ms?

**Comment by ImLunaHey** [comment]
pretty sure it's request 1 in 1ms, request 2 in 2ms, so in essence theyre 1ms after each other.

**Comment by username-is-required** [comment]
@ImLunaHey thank you, i am officially stupid

slightly surprised that reddit doesn’t rate limit the hell out of things with a request every ms, but hey that’s a good thing
