### ISSUE TITLE
Suggestion: Add the countdown timer

### ISSUE THREAD

**Issue by ayub407** [Tanza3D/reddark#36]
I think it would be informative to add the countdown timer for the blackout to start and then change to the countdown for the blackout to end, that way users can see what all subreddits that became private and then which all subreddits are still private even after the blackout period has ended.

Maybe something like this
![Screenshot_20230611_180531_Hurry](https://github.com/Tanza3D/reddark/assets/136248454/c7ae4752-293a-466b-92e0-bbf9214c305b)

**Comment by wilkgr76** [comment]
I don't think there's a specific timezone that had been chosen - it's already 2023-06-12 in eastern Australia and New Zealand, for instance, but obviously still a ways away in other timezones such as in the US or Europe. Subreddits are likely to go private based on the moderators' timezones.

**Comment by Tanza3D** [comment]
yeah, there's no specific time from my knowledge, i won't be adding a countdown unless one is decided
