### ISSUE TITLE
Website needs some padding (at least on mobile)

### ISSUE THREAD

**Issue by username-is-required** [Tanza3D/reddark#5]
Not sure how the page looks on desktop at the moment, but just wanted to let you know that on mobile (Safari on iOS), the page needs a bit of padding around the edges. Screenshot attached.

![IMG_9285](https://github.com/Tanza3D/reddark/assets/136007111/46b552dc-2168-436f-add5-3064057e6ff3)

Absolutely *loving* the website so far! Especially given the [recent update](https://reddit.com/r/apolloapp/comments/144f6xm/apollo_will_close_down_on_june_30th_reddits/) from Apollo devs, I will very much like watching live as all the subs go dark.

**Comment by Tanza3D** [comment]
ah yeah, i always forget about mobile. will get that sorted!
