### ISSUE TITLE
Site returns 404

### ISSUE THREAD

**Issue by DevilXD** [Tanza3D/reddark#54]
Is the site down? It started returning 403 for like 10 minutes, now it's 404 for quite a while now.

![obraz](https://github.com/Tanza3D/reddark/assets/4180725/a9eb3a9a-eb41-4719-8877-f55085a5ada7)

**Comment by KonradStuewe** [comment]
Seems to be back for now.
Alternatively, there is the live stream and a couple of forks.
https://www.twitch.tv/reddark_247
https://reddark-digitalocean-7lhfr.ondigitalocean.app/
http://lknm.duckdns.org/

**Comment by DevilXD** [comment]
Alright, thank you =)
