### ISSUE TITLE
Showing some subreddits as private when they’re still open

### ISSUE THREAD

**Issue by username-is-required** [Tanza3D/reddark#7]
Sorry if you’re already aware of this! Not sure if it’s a Reddit issue or not, but just wanted to notify you that some of the subreddits currently listed as `private` are actually still open (for now).

Examples:
 - r/MorbidReality
 - r/CrimeScene
 - r/MedicalGore

![IMG_9286](https://github.com/Tanza3D/reddark/assets/136007111/e38dfb05-7320-4eaf-8cfd-82e2c1ad5f3f)

Again sorry if you’re already aware of this and for spamming you with issues! Just wanted to raise it now in case it would impact the site on June 12th :)

**Comment by Tanza3D** [comment]
hm, seems weird, will look into it in a bit. was just really dumb and pushed some fucky code so that might just be it, but i do remember seeing these when testing alot. might be because they're nsfw subs?

**Comment by username-is-required** [comment]
FWIW I noticed these subreddits on the site before the now-deleted push (which I saw on the commit log while trying to figure out if it might have been *fixed* by the change, funnily enough).

**Comment by Tanza3D** [comment]
think i've fixed it now! thanks for the report :3

**Comment by Tanza3D** [comment]
if there is any more issues, please do report them! better to have them fixed now than be flooded on june 12th!

**Comment by Tanza3D** [comment]
as long as you don't look at the code :^)
