### ISSUE TITLE
Why are there missing subreddits?

### ISSUE THREAD

**Issue by tansanDOTeth** [Tanza3D/reddark#77]
I noticed not all subreddits are listed. Is there a reason for this?

**Comment by MaxDeVos** [comment]
Only subreddits that indicated that they would be participating are shown. They are listed [here](https://www.reddit.com/r/ModCoord/wiki/index/)

**Comment by tansanDOTeth** [comment]
@MaxDeVos Got it! Thanks for clarifying!
